version: '3.8'

services:
  web:
    image: nginx
    container_name: web
    ports:
      - "8080:80"
    volumes:
      - ./:/usr/share/nginx/html
    stdin_open: true
    tty: true
    restart: no
